[package]
name = "box_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
obj-rs = "0.7.4"
smallvec = { version = "1.13.2", features = ["union"] }
clap = { version = "4.5.20", features = ["derive"] }
[profile.dev]
opt-level = 3
